artifact_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  data_path: alzimer_img
  
  
prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.keras
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.keras


training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.keras
  training_data_path: artifacts/data_ingestion/alzimer_img
  
  